package cat.naval.xamanta.models

object PreferenceConstants {
    const val PREFERENCES = "PREFERENCES"
    const val CONNECTION_SETTINGS = "CONNECTION_SETTINGS"
    const val CURRENT_POLICY = "CURRENT_POLICY"

    const val ANSWERED_COMMANDS = "ANSWERED_COMMANDS"

    const val KIOSK_DEGRADED_PACKAGE = "KIOSK_DEGRADED_PACKAGE"
    const val LOCK_TASK_PINNED_PACKAGE = "LOCK_TASK_PINNED_PACKAGE"
    const val KIOSK_LAUNCH_WINDOW_START = "KIOSK_LAUNCH_WINDOW_START"
    const val KIOSK_LAUNCH_COUNT = "KIOSK_LAUNCH_COUNT"

    const val KIOSK_LAUNCHED_PACKAGE = "KIOSK_LAUNCHED_PACKAGE"

    const val KIOSK_UNPINNED_PACKAGE = "KIOSK_UNPINNED_PACKAGE"

    const val PREFERRED_ACTIVITY_PACKAGES = "PREFERRED_ACTIVITY_PACKAGES"
    const val MANAGED_APPLICATION_PACKAGES = "MANAGED_APPLICATION_PACKAGES"
    const val WIFI_ROAMING_SSIDS = "WIFI_ROAMING_SSIDS"
    const val PROVISIONED_NETWORKS = "PROVISIONED_NETWORKS"

    const val PROVISIONED_NETWORK_RECORDS = "PROVISIONED_NETWORK_RECORDS"
    const val PROVISIONED_KEY_ALIASES = "PROVISIONED_KEY_ALIASES"
    const val PROVISIONED_CA_CERTS = "PROVISIONED_CA_CERTS"
    const val OVERRIDE_APN_IDS = "OVERRIDE_APN_IDS"

    const val RESET_PASSWORD_TOKEN = "RESET_PASSWORD_TOKEN"

    const val EXTRA_ENROLLMENT_TOKEN = "EXTRA_ENROLLMENT_TOKEN"
    const val EXTRA_TOKEN_ENDPOINT = "EXTRA_TOKEN_ENDPOINT"
    const val EXTRA_GRPC_HOST = "EXTRA_GRPC_HOST"
    const val EXTRA_GRPC_PORT = "EXTRA_GRPC_PORT"

    const val EXTRA_SERVER_CA_CERT = "EXTRA_SERVER_CA_CERT"

    const val OAUTH_CLIENT_ID = "OAUTH_CLIENT_ID"
    const val CLIENT_SECRET = "CLIENT_SECRET"

    const val AUTH_TOKEN = "AUTH_TOKEN"

    const val NEEDS_REENROLLMENT = "NEEDS_REENROLLMENT"
    const val LAST_AUTH_ERROR = "LAST_AUTH_ERROR"
}
